pool:
   vmImage: 'macOS 10.13'
   
steps:
- script: |
    sudo xcode-select -switch /Applications/Xcode_10.app
  displayName: "Setup environment"

- script: |
    fastlane build
  displayName: "Build"

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: "build"
    artifactName: "Build logs"
  condition: succeededOrFailed()
  displayName: "Store build log"

- script: |
    fastlane test
  displayName: "Test"

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: "test"
    artifactName: "Test logs"
  condition: succeededOrFailed()
  displayName: "Store test log"